openapi: 3.1.0
info:
  title: 'Admin Authentication: Customer Login'
  version: 1.0.0
paths:
  /login/token/{jwt_token}:
    get:
      operationId: loginToken_getCustomerLogin
      summary: Login Token
      description: >-
        The customer login access point URL.


        [Learn more about the Customer Login
        API](/developer/docs/storefront/guides/customer-authentication/customer-login).


        ## Example


        ```

        https://yourstore.example.com/login/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ7Y2xpZW50X2lkfSIsImlhdCI6MTUzNTM5MzExMywianRpIjoie3V1aWR9Iiwib3BlcmF0aW9uIjoiY3VzdG9tZXJfbG9naW4iLCJzdG9yZV9oYXNoIjoie3N0b3JlX2hhc2h9IiwiY3VzdG9tZXJfaWQiOjJ9.J-fAtbjRFGdLsT744DhoprFEDqIfVq72HbDzrbFy6Is

        ```
      tags:
        - loginToken
      parameters:
        - name: jwt_token
          in: path
          description: The JWT that authenticates the customer login request.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login_Token_getCustomerLogin_Response_200'
tags:
  - name: loginToken
    description: Generate a login token that authenticates a customer and starts a storefront session.
servers:
  - url: https://your_store.example.com
    description: https://{store_domain}
components:
  schemas:
    Login_Token_getCustomerLogin_Response_200:
      type: object
      properties: {}
      description: Empty response body
      title: Login Token_getCustomerLogin_Response_200
