openapi: 3.1.0
info:
  title: "Admin Management: Pickup"
  version: 1.0.0
paths:
  /stores/{store_hash}/v3/pickup/options:
    post:
      operationId: pickupOptions_post-pickup-options
      summary: Find Available Pickup Options
      description: |-
        Returns up to 10 available pickup options for the requested items around a radius of the provided search coordinates. 

        The pickup options returned only include options where all requested items are available and can be picked up from a single location.
      tags:
        - pickupOptions
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        "200":
          description: The request has been successfully processed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickupOptionsResponse"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PickupRequestPayload"
      security:
        - X-Auth-Token: []
tags:
  - name: pickup
    description: BigCommerce Pickup API Definition.
  - name: pickupMethods
    description: BigCommerce Pickup Methods API Definition.
  - name: pickupOptions
    description: BigCommerce Pickup Options V3 Definition.
servers:
  - url: https://api.bigcommerce.com
    description: https://api.bigcommerce.com
components:
  schemas:
    PickupRequestPayload:
      type: object
      properties:
        search_area:
          $ref: "#/components/schemas/SearchArea"
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
          description: Items you include in your search for pickup options.
      required:
        - search_area
        - items
      title: PickupRequestPayload
    Item:
      type: object
      properties:
        variant_id:
          type: integer
        quantity:
          type: integer
      required:
        - variant_id
        - quantity
      title: Item
    SearchArea:
      type: object
      properties:
        coordinates:
          $ref: "#/components/schemas/Coordinates"
        radius:
          $ref: "#/components/schemas/SearchAreaRadius"
          description: Radius around the coordinates where you are searching for pickup options.
      required:
        - radius
      description: Area where you are searching for pickup options.
      title: SearchArea
    SearchAreaRadius:
      type: object
      properties:
        value:
          type: integer
        unit:
          $ref: "#/components/schemas/SearchAreaRadiusUnit"
      required:
        - value
        - unit
      description: Radius around the coordinates where you are searching for pickup options.
      title: SearchAreaRadius
    SearchAreaRadiusUnit:
      type: string
      enum:
        - KM
        - MI
      title: SearchAreaRadiusUnit
    Coordinates:
      type: object
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
      required:
        - latitude
        - longitude
      description: Coordinates where you are searching for pickup options.
      title: Coordinates
    PickupOptionsResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/PickupOptionsResponseResultsItems"
      title: PickupOptionsResponse
    PickupOptionsResponseResultsItems:
      type: object
      properties:
        pickup_options:
          type: array
          items:
            $ref: "#/components/schemas/PickupOption"
          description: Pickup options for the available items.
      title: PickupOptionsResponseResultsItems
    PickupOption:
      type: object
      properties:
        pickup_method:
          $ref: "#/components/schemas/PickupMethod"
        available_items:
          type: array
          items:
            $ref: "#/components/schemas/AvailableItem"
          description: Items that are available using the pickup method.
      title: PickupOption
    AvailableItem:
      type: object
      properties:
        variant_id:
          type: integer
        quantity:
          type: integer
      title: AvailableItem
    PickupMethod:
      type: object
      properties:
        id:
          type: integer
        location_id:
          type: integer
        display_name:
          type: string
          minLength: 0
          maxLength: 250
        collection_instructions:
          type: string
          minLength: 0
          maxLength: 250
        collection_time_description:
          type: string
          minLength: 0
          maxLength: 250
      description: Pickup method that can be used with the available items.
      title: PickupMethod
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |-
        ### OAuth scopes

        | UI Name | Permission | Parameter |
        |:--------|:-----------|:----------|
        |  Order Fulfillment | read-only | `store_order_fulfillment_read_only` | 
        |  Order Fulfillment | modify | `store_order_fulfillment_manage` |

        ### Authentication header

        | Header | Argument | Description |
        |:-------|:---------|:------------|
        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see [API Accounts and OAuth Scopes](/developer/docs/overview/api-fundamentals/api-accounts#api-accounts). |

        ### Further reading

        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/developer/docs/overview/api-fundamentals/api-accounts).

        For more about BigCommerce OAuth scopes, see [API Accounts and OAuth Scopes](/developer/docs/overview/api-fundamentals/api-accounts#oauth-scopes).

        For a list of API status codes, see [API Status Codes](/developer/api-reference/rest/overview#rest-http-status-codes).
