openapi: 3.1.0
info:
  title: "Admin Management: Pickup"
  version: 1.0.0
paths:
  /stores/{store_hash}/v3/pickup/methods:
    get:
      operationId: pickupMethods_get-pickup-methods
      summary: List Pickup Methods
      description: |-
        Retrieves a list of pickup methods.

        ## Examples

        You can filter this list to return pickup method objects specific to a list of requested pickup method IDs. This is achieved by appending the query string `?id:in=1,3,5` to the resource `/pickup/methods`.

        ```http
        GET /pickup/methods?id:in=1,3,5
        ```
      tags:
        - pickupMethods
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: id:in
          in: query
          description: Comma separated list of pickup method IDs.
          required: false
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: Maximum number of results per page.
          required: false
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          description: The number of the page to be fetched.
          required: false
          schema:
            type: integer
            format: int64
        - name: date_created
          in: query
          description: |-
            Filter pickup methods by the date created. Return methods created on the provided date.

            For example, `date_created=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: date_created:min
          in: query
          description: |-
            Filter pickup methods by minimum date created. Return methods created after the provided date.

            For example, `date_created:min=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: date_created:max
          in: query
          description: |-
            Filter pickup methods by maximum date created. Return methods created before the provided date.

            For example, `date_created:max=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: date_modified
          in: query
          description: |-
            Filter pickup methods by date modified. Return methods modified on the provided date.

            For example, `date_modified=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: date_modified:min
          in: query
          description: |-
            Filter pickup methods by minimum date modified. Return methods modified after the provided date.

            For example, `date_modified:min=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: date_modified:max
          in: query
          description: |-
            Filter pickup methods by maximum date modified. Return methods modified before the provided date.

            For example, `date_modified:max=2023-09-07T06:23:13Z`.
          required: false
          schema:
            type: string
            format: date-time
        - name: sort
          in: query
          description: |-
            Sort pickup methods by date_modified:* or name:* ; for example, `sort=name:asc`.  

            - `date_modified:asc` - sort by date modified in ascending order
            - `date_modified:desc` - sort by date modified in descending order
            - `name:asc` - sort by name in ascending order
            - `name:desc` - sort by name in descending order
          required: false
          schema:
            $ref: "#/components/schemas/PickupMethodsGetParametersSort"
        - name: Accept
          in: header
          description: The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        "200":
          description: The request has been processed and a list of pickup methods has been returned successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pickup_Methods_get-pickup-methods_Response_200"
      security:
        - X-Auth-Token: []
    post:
      operationId: pickupMethods_post-pickup-methods
      summary: Create Pickup Methods
      description: |-
        Creates one or many pickup methods.

        This is a batch operation that can create up to 100 pickup methods objects in one request.

        ## Limits
        * Limit of creating 100 pickup method objects per `POST` request.
      tags:
        - pickupMethods
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        "200":
          description: The request has been successfully processed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pickup_Methods_post-pickup-methods_Response_200"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/BasePickupMethod"
      security:
        - X-Auth-Token: []
    put:
      operationId: pickupMethods_put-pickup-methods
      summary: Update Pickup Methods
      description: |-
        Update existing pickup methods.

        This batch operation can update 10 pickup method objects in one request.

        Only the `id` property of the pickup method object is required as part of the request. Pickup method properties that are not provided will maintain their existing values.

        ## Limits
        * Limit of updating 10 pickup method objects per `PUT` request.
      tags:
        - pickupMethods
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        "200":
          description: The request has been successfully processed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pickup_Methods_put-pickup-methods_Response_200"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/PickupMethodsPutRequestBodyContentApplicationJsonSchemaItems"
      security:
        - X-Auth-Token: []
    delete:
      operationId: pickupMethods_delete-pickup-methods
      summary: Delete Pickup Methods
      description: Delete existing pickup methods.
      tags:
        - pickupMethods
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: id:in
          in: query
          description: Comma separated list of pickup method IDs.
          required: true
          schema:
            type: integer
            format: int64
        - name: Accept
          in: header
          description: The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        "204":
          description: No Content
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - X-Auth-Token: []
tags:
  - name: pickup
    description: BigCommerce Pickup API Definition.
  - name: pickupMethods
    description: BigCommerce Pickup Methods API Definition.
  - name: pickupOptions
    description: BigCommerce Pickup Options V3 Definition.
servers:
  - url: https://api.bigcommerce.com
    description: https://api.bigcommerce.com
components:
  schemas:
    PickupMethodsPutRequestBodyContentApplicationJsonSchemaItems:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the pickup method.
        location_id:
          type: integer
          description: The ID of the location.
        display_name:
          type: string
          minLength: 0
          maxLength: 250
          description: Title of the pickup method.
        collection_instructions:
          type: string
          minLength: 0
          maxLength: 250
          description: Instructions for picking up items.
        collection_time_description:
          type: string
          minLength: 0
          maxLength: 250
          description: The description of collection time.
        location_identity:
          type: integer
          deprecated: true
      title: PickupMethodsPutRequestBodyContentApplicationJsonSchemaItems
    Pickup_Methods_put-pickup-methods_Response_200:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PickupMethodResponse"
        meta:
          $ref: "#/components/schemas/PickupMethodsPutResponsesContentApplicationJsonSchemaMeta"
      title: Pickup Methods_put-pickup-methods_Response_200
    PickupMethodsPutResponsesContentApplicationJsonSchemaMeta:
      type: object
      properties: {}
      title: PickupMethodsPutResponsesContentApplicationJsonSchemaMeta
    PickupMethodResponse:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the pickup method.
        location_id:
          type: integer
          description: The ID of the location.
        display_name:
          type: string
          minLength: 0
          maxLength: 250
          description: Title of the pickup method.
        collection_instructions:
          type: string
          minLength: 0
          maxLength: 250
          description: Instructions for picking up items.
        collection_time_description:
          type: string
          minLength: 0
          maxLength: 250
          description: The description of collection time.
        location_identity:
          type: integer
          deprecated: true
        date_created:
          type: string
          format: date-time
          description: |-
            Filter pickup methods by time created.

            Time is presented in ISO-8601 format.
        date_modified:
          type: string
          format: date-time
          description: |-
            Filter pickup methods by time modified.

            Time is presented in ISO-8601 format.
      title: PickupMethodResponse
    BasePickupMethod:
      type: object
      properties:
        location_id:
          type: integer
          description: The ID of the location.
        display_name:
          type: string
          minLength: 0
          maxLength: 250
          description: Title of the pickup method.
        collection_instructions:
          type: string
          minLength: 0
          maxLength: 250
          description: Instructions for picking up items.
        collection_time_description:
          type: string
          minLength: 0
          maxLength: 250
          description: The description of collection time.
        location_identity:
          type: integer
          deprecated: true
      title: BasePickupMethod
    Pickup_Methods_post-pickup-methods_Response_200:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PickupMethodResponse"
        meta:
          $ref: "#/components/schemas/PickupMethodsPostResponsesContentApplicationJsonSchemaMeta"
      title: Pickup Methods_post-pickup-methods_Response_200
    PickupMethodsPostResponsesContentApplicationJsonSchemaMeta:
      type: object
      properties: {}
      title: PickupMethodsPostResponsesContentApplicationJsonSchemaMeta
    Pickup_Methods_get-pickup-methods_Response_200:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PickupMethodResponse"
        meta:
          $ref: "#/components/schemas/MetaCollection"
      title: Pickup Methods_get-pickup-methods_Response_200
    MetaCollection:
      type: object
      properties:
        pagination:
          $ref: "#/components/schemas/MetaCollectionPagination"
      title: MetaCollection
    MetaCollectionPagination:
      type: object
      properties:
        total:
          type: integer
          description: Total number of items in the result set.
        count:
          type: integer
          description: The total number of items in the collection on the current page.
        per_page:
          type: integer
          description: The amount of items returned in the collection per page, controlled by the limit parameter.
        current_page:
          type: integer
          description: The page you are currently on within the collection.
        total_pages:
          type: integer
          description: The total number of pages in the collection.
        links:
          $ref: "#/components/schemas/MetaCollectionPaginationLinks"
          description: Pagination links for the previous and next parts of the whole collection.
      title: MetaCollectionPagination
    MetaCollectionPaginationLinks:
      type: object
      properties:
        previous:
          type: string
          description: A link to the previous page is returned in the response.
        current:
          type: string
          description: A link to the current page is returned in the response.
        next:
          type: string
          description: A link to the next page is returned in the response.
      description: Pagination links for the previous and next parts of the whole collection.
      title: MetaCollectionPaginationLinks
    PickupMethodsGetParametersSort:
      type: string
      enum:
        - date_modified:asc
        - date_modified:desc
        - name:asc
        - name:desc
      title: PickupMethodsGetParametersSort
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |-
        ### OAuth scopes

        | UI Name | Permission | Parameter |
        |:--------|:-----------|:----------|
        |  Order Fulfillment | read-only | `store_order_fulfillment_read_only` | 
        |  Order Fulfillment | modify | `store_order_fulfillment_manage` |

        ### Authentication header

        | Header | Argument | Description |
        |:-------|:---------|:------------|
        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see [API Accounts and OAuth Scopes](/developer/docs/overview/api-fundamentals/api-accounts#api-accounts). |

        ### Further reading

        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/developer/docs/overview/api-fundamentals/api-accounts).

        For more about BigCommerce OAuth scopes, see [API Accounts and OAuth Scopes](/developer/docs/overview/api-fundamentals/api-accounts#oauth-scopes).

        For a list of API status codes, see [API Status Codes](/developer/api-reference/rest/overview#rest-http-status-codes).
