openapi: 3.1.0
info:
  title: 'Admin Management: Tax Classes V2'
  version: 1.0.0
paths:
  /stores/{store_hash}/v2/tax_classes:
    get:
      operationId: taxClasses_getTaxClasses
      summary: List Tax Classes
      description: |-
        Returns a list of all *Tax Classes* in a store.

        Default sorting is by tax-class id, from lowest to highest.
      tags:
        - taxClasses
      parameters:
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: >-
            The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response
            body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/taxClass_Full'
      security:
        - X-Auth-Token: []
  /stores/{store_hash}/v2/tax_classes/{id}:
    get:
      operationId: taxClasses_getTaxClass
      summary: Get Tax Class
      description: Returns a single *Tax Class*.
      tags:
        - taxClasses
      parameters:
        - name: id
          in: path
          description: ID of the tax class.
          required: true
          schema:
            type: integer
        - name: store_hash
          in: path
          description: Permanent ID of the BigCommerce store.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: >-
            The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response
            body.
          required: true
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taxClass_Full'
      security:
        - X-Auth-Token: []
tags:
  - name: taxClasses
    description: Retrieve the tax classes a store defines.
servers:
  - url: https://api.bigcommerce.com
    description: https://api.bigcommerce.com
components:
  schemas:
    taxClass_Full:
      type: object
      properties:
        id:
          type: string
          description: >-
            The unique numerical ID of the tax class. A read-only value which is automatically assigned and increments
            sequentially.
        name:
          type: string
          description: The name of the tax class.
        created_at:
          type: string
          format: date-time
          description: Date and time of the tax class' creation. Read-Only.
        updated_at:
          type: string
          format: date-time
          description: Date and time when the tax class was last updated. Read-Only.
      title: taxClass_Full
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: >-
        ### OAuth scopes


        | UI Name | Permission | Parameter |

        |:--------|:-----------|:----------|

        |  Information & Settings | modify | `store_v2_information` |

        |  Information & Settings | read-only | `store_v2_information_read_only` |


        ### Authentication header


        | Header | Argument | Description |

        |:-------|:---------|:------------|

        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see our [Guide to
        API Accounts](/developer/docs/overview/api-fundamentals/api-accounts#api-accounts). |


        ### Further reading


        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example
        Requests](/developer/docs/overview/api-fundamentals/api-accounts#x-auth-token-header-example-requests).


        For more about BigCommerce OAuth scopes, see our [Guide to API
        Accounts](/developer/docs/overview/api-fundamentals/api-accounts#oauth-scopes).


        For a list of API status codes, see [API Status
        Codes](/developer/api-reference/rest/overview#rest-http-status-codes).
