import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as ScriptsV3ApiSpecs from '../generated/scripts-v3';
export * as ScriptsV3ApiSpecs from '../generated/scripts-v3';

export class ScriptsV3Api {
    private readonly request: RequestService;

    constructor(request: RequestService) {
        this.request = request;
    }

    /**
     * Get All Scripts
     *
     * Returns a list of *Scripts*. Optional parameters can be passed in.

     This operation will only return scripts generated by the API key and password used to create the script originally. 
     */
    getScripts(
        query?: ScriptsV3ApiSpecs.GetScriptsData['query'],
    ) {
        return this.request.get<RequestSuccessResponse<200, Required<ScriptsV3ApiSpecs.GetScriptsResponses[200]>>,RequestErrorResponse<422, Required<ScriptsV3ApiSpecs.GetScriptsErrors[422]>>>({
            path: 'v3/content/scripts',
            query,
        });
    }

    /**
     * Create a Script
     *
     * Creates a *Script*.

     **Required Fields**
     * name

     **Read Only Fields**
     * uuid

     **Limits**
     * 50 scripts per channel.

     **Notes**
     * If the `kind` is `src`:
       * Specify the `src` property. 
       * Optionally, you can supply a `load_method`. 
       * Do not specify the `html` field.
     * If the `kind` is `script_tag`:
       * Specify the `html` property.
       * Do not specify the `src` field.
     * Each app can have 10 scripts installed.
     * Multiple scripts can be created [per call](/docs/integrations/scripts#notes). 
     */
    createScript(
        requestBody: ScriptsV3ApiSpecs.CreateScriptData['body'],
    ) {
        return this.request.post<RequestSuccessResponse<200, Required<ScriptsV3ApiSpecs.CreateScriptResponses[200]>>,RequestErrorResponse<422, Required<ScriptsV3ApiSpecs.CreateScriptErrors[422]>>>({
            path: 'v3/content/scripts',
            contentType: 'application/json',
            body: requestBody,
        });
    }

    /**
     * Get a Script
     *
     * Returns a single *Script*.
     */
    getScript(
        uuid: ScriptsV3ApiSpecs.GetScriptData['path']['uuid'],
    ) {
        return this.request.get<RequestSuccessResponse<200, Required<ScriptsV3ApiSpecs.GetScriptResponses[200]>>,(RequestErrorResponse<404, Required<ScriptsV3ApiSpecs.GetScriptErrors[404]>> | RequestErrorResponse<422, Required<ScriptsV3ApiSpecs.GetScriptErrors[422]>>)>({
            path: `v3/content/scripts/${uuid}`,
        });
    }

    /**
     * Update a Script
     *
     * Updates a *Script*.
     */
    updateScript(
        uuid: ScriptsV3ApiSpecs.UpdateScriptData['path']['uuid'],
        requestBody: ScriptsV3ApiSpecs.UpdateScriptData['body'],
    ) {
        return this.request.put<RequestSuccessResponse<200, Required<ScriptsV3ApiSpecs.UpdateScriptResponses[200]>>,(RequestErrorResponse<404, Required<ScriptsV3ApiSpecs.UpdateScriptErrors[404]>> | RequestErrorResponse<422, Required<ScriptsV3ApiSpecs.UpdateScriptErrors[422]>>)>({
            path: `v3/content/scripts/${uuid}`,
            contentType: 'application/json',
            body: requestBody,
        });
    }

    /**
     * Delete a Script
     *
     * Deletes a *Script*.
     */
    deleteScript(
        uuid: ScriptsV3ApiSpecs.DeleteScriptData['path']['uuid'],
    ) {
        return this.request.delete<RequestSuccessResponse<204, Required<ScriptsV3ApiSpecs.DeleteScriptResponses[204]>>,(RequestErrorResponse<404, Required<ScriptsV3ApiSpecs.DeleteScriptErrors[404]>> | RequestErrorResponse<422, Required<ScriptsV3ApiSpecs.DeleteScriptErrors[422]>>)>({
            path: `v3/content/scripts/${uuid}`,
        });
    }
}
