import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as BrandsV3ApiSpecs from '../generated/brands-v3';
export * as BrandsV3ApiSpecs from '../generated/brands-v3';
export declare class BrandsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getBrands(query?: BrandsV3ApiSpecs.GetBrandsData['query']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.BrandsGetBrandsResponse200>> | RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>>>;
    createBrand(requestBody: BrandsV3ApiSpecs.CreateBrandData['body']): Promise<RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>> | RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.BrandsCreateBrandResponse200>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.NotFoundError>> | RequestErrorResponse<409, Required<BrandsV3ApiSpecs.CreateBrandRequestConflictError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.CreateBrandRequestUnprocessableEntityError>>>;
    deleteBrands(query?: BrandsV3ApiSpecs.DeleteBrandsData['query']): Promise<RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.ErrorBase>>>;
    getBrand(brandId: BrandsV3ApiSpecs.GetBrandData['path']['brand_id'], query?: BrandsV3ApiSpecs.GetBrandData['query']): Promise<RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>> | RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.BrandsGetBrandResponse200>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.GetBrandRequestNotFoundError>> | RequestErrorResponse<409, Required<BrandsV3ApiSpecs.Conflict>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs._Error>>>;
    updateBrand(brandId: BrandsV3ApiSpecs.UpdateBrandData['path']['brand_id'], requestBody: BrandsV3ApiSpecs.UpdateBrandData['body']): Promise<RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>> | RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.BrandsUpdateBrandResponse200>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.UpdateBrandRequestNotFoundError>> | RequestErrorResponse<409, Required<BrandsV3ApiSpecs.UpdateBrandRequestConflictError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.UpdateBrandRequestUnprocessableEntityError>>>;
    deleteBrand(brandId: BrandsV3ApiSpecs.DeleteBrandData['path']['brand_id']): Promise<RequestErrorResponse<403, Required<BrandsV3ApiSpecs.ErrorBase>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.NotFoundError>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getBrandsMetafields(query?: BrandsV3ApiSpecs.GetBrandsMetafieldsData['query']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetaFieldCollectionResponse>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.GetBrandsMetafieldsRequestBadRequestError>>>;
    createBrandsMetafields(requestBody: BrandsV3ApiSpecs.CreateBrandsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.CreateBrandsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateBrandsMetafields(requestBody: BrandsV3ApiSpecs.UpdateBrandsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.UpdateBrandsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.UpdateBrandsMetafieldsRequestUnprocessableEntityError>>>;
    deleteBrandsMetafields(requestBody: BrandsV3ApiSpecs.DeleteBrandsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.DeleteBrandsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    createBrandImage(brandId: BrandsV3ApiSpecs.CreateBrandImageData['path']['brand_id'], requestBody: BrandsV3ApiSpecs.CreateBrandImageData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.ImagesCreateBrandImageResponse200>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.CreateBrandImageRequestBadRequestError>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.CreateBrandImageRequestNotFoundError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.CreateBrandImageRequestUnprocessableEntityError>>>;
    deleteBrandImage(brandId: BrandsV3ApiSpecs.DeleteBrandImageData['path']['brand_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getBrandMetafields(brandId: BrandsV3ApiSpecs.GetBrandMetafieldsData['path']['brand_id'], query?: BrandsV3ApiSpecs.GetBrandMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetafieldsGetBrandMetafieldsResponse200>>>;
    createBrandMetafield(brandId: BrandsV3ApiSpecs.CreateBrandMetafieldData['path']['brand_id'], requestBody: BrandsV3ApiSpecs.CreateBrandMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetafieldsCreateBrandMetafieldResponse200>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.CreateBrandMetafieldRequestBadRequestError>> | RequestErrorResponse<409, Required<BrandsV3ApiSpecs.CreateBrandMetafieldRequestConflictError>> | RequestErrorResponse<422, Required<BrandsV3ApiSpecs.CreateBrandMetafieldRequestUnprocessableEntityError>>>;
    getBrandMetafield(brandId: BrandsV3ApiSpecs.GetBrandMetafieldData['path']['brand_id'], metafieldId: BrandsV3ApiSpecs.GetBrandMetafieldData['path']['metafield_id'], query?: BrandsV3ApiSpecs.GetBrandMetafieldData['query']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetafieldsGetBrandMetafieldResponse200>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.GetBrandMetafieldRequestNotFoundError>>>;
    updateBrandMetafield(brandId: BrandsV3ApiSpecs.UpdateBrandMetafieldData['path']['brand_id'], metafieldId: BrandsV3ApiSpecs.UpdateBrandMetafieldData['path']['metafield_id'], requestBody: BrandsV3ApiSpecs.UpdateBrandMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<BrandsV3ApiSpecs.MetafieldsUpdateBrandMetafieldResponse200>> | RequestErrorResponse<400, Required<BrandsV3ApiSpecs.UpdateBrandMetafieldRequestBadRequestError>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.UpdateBrandMetafieldRequestNotFoundError>>>;
    deleteBrandMetafield(brandId: BrandsV3ApiSpecs.DeleteBrandMetafieldData['path']['brand_id'], metafieldId: BrandsV3ApiSpecs.DeleteBrandMetafieldData['path']['metafield_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<BrandsV3ApiSpecs.DeleteBrandMetafieldRequestNotFoundError>>>;
}
