import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as CartsV3ApiSpecs from '../generated/carts-v3';
export * as CartsV3ApiSpecs from '../generated/carts-v3';
export declare class CartsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getCartsMetafields(query?: CartsV3ApiSpecs.GetCartsMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionResponseBatch>>>;
    createCartsMetafields(requestBody: CartsV3ApiSpecs.CreateCartsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionResponseBatchPostPut>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.CreateCartsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CartsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateCartsMetafields(requestBody: CartsV3ApiSpecs.UpdateCartsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionResponseBatchPostPut>> | RequestErrorResponse<422, Required<CartsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.UpdateCartsMetafieldsRequestBadRequestError>>>;
    deleteCartsMetafields(requestBody: CartsV3ApiSpecs.DeleteCartsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.DeleteCartsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CartsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    createCart(requestBody: CartsV3ApiSpecs.CreateCartData['body'], query?: CartsV3ApiSpecs.CreateCartData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<201, Required<CartsV3ApiSpecs.CartsSingleCreateCartResponse201>>>;
    getCart(cartId: CartsV3ApiSpecs.GetCartData['path']['cartId'], query?: CartsV3ApiSpecs.GetCartData['query']): Promise<RequestErrorResponse<404, Required<unknown>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.CartsSingleGetCartResponse200>>>;
    updateCart(cartId: CartsV3ApiSpecs.UpdateCartData['path']['cartId'], requestBody: CartsV3ApiSpecs.UpdateCartData['body'], query?: CartsV3ApiSpecs.UpdateCartData['query']): Promise<RequestSuccessResponse<201, Required<CartsV3ApiSpecs.CartsSingleUpdateCartResponse201>> | RequestErrorResponse<409, Required<CartsV3ApiSpecs.ErrorResponse>>>;
    deleteCart(cartId: CartsV3ApiSpecs.DeleteCartData['path']['cartId']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    addCartLineItems(cartId: CartsV3ApiSpecs.AddCartLineItemsData['path']['cartId'], requestBody: CartsV3ApiSpecs.AddCartLineItemsData['body'], query?: CartsV3ApiSpecs.AddCartLineItemsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<201, Required<CartsV3ApiSpecs.ItemsAddCartLineItemsResponse201>>>;
    updateCartLineItem(cartId: CartsV3ApiSpecs.UpdateCartLineItemData['path']['cartId'], itemId: CartsV3ApiSpecs.UpdateCartLineItemData['path']['itemId'], requestBody: CartsV3ApiSpecs.UpdateCartLineItemData['body'], query?: CartsV3ApiSpecs.UpdateCartLineItemData['query']): Promise<RequestErrorResponse<409, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.ItemsUpdateCartLineItemResponse200>>>;
    deleteCartLineItem(cartId: CartsV3ApiSpecs.DeleteCartLineItemData['path']['cartId'], itemId: CartsV3ApiSpecs.DeleteCartLineItemData['path']['itemId'], requestBody: CartsV3ApiSpecs.DeleteCartLineItemData['body'], query?: CartsV3ApiSpecs.DeleteCartLineItemData['query']): Promise<RequestErrorResponse<409, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.CartFull>>>;
    getCartMetafields(cartId: CartsV3ApiSpecs.GetCartMetafieldsData['path']['cart_id'], query?: CartsV3ApiSpecs.GetCartMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetafieldResponse>>>;
    createCartMetafield(cartId: CartsV3ApiSpecs.CreateCartMetafieldData['path']['cart_id'], requestBody: CartsV3ApiSpecs.CreateCartMetafieldData['body']): Promise<RequestErrorResponse<409, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionResponse>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.CreateCartMetafieldRequestBadRequestError>> | RequestErrorResponse<422, Required<CartsV3ApiSpecs.ErrorResponse>>>;
    getCartMetafield(cartId: CartsV3ApiSpecs.GetCartMetafieldData['path']['cart_id'], metafieldId: CartsV3ApiSpecs.GetCartMetafieldData['path']['metafield_id'], query?: CartsV3ApiSpecs.GetCartMetafieldData['query']): Promise<RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetafieldResponse>> | RequestErrorResponse<404, Required<CartsV3ApiSpecs.NotFound>>>;
    updateCartMetafield(cartId: CartsV3ApiSpecs.UpdateCartMetafieldData['path']['cart_id'], metafieldId: CartsV3ApiSpecs.UpdateCartMetafieldData['path']['metafield_id'], requestBody: CartsV3ApiSpecs.UpdateCartMetafieldData['body']): Promise<RequestErrorResponse<422, Required<CartsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.MetaFieldCollectionResponse>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.UpdateCartMetafieldRequestBadRequestError>>>;
    deleteCartMetafield(cartId: CartsV3ApiSpecs.DeleteCartMetafieldData['path']['cart_id'], metafieldId: CartsV3ApiSpecs.DeleteCartMetafieldData['path']['metafield_id']): Promise<RequestErrorResponse<404, Required<CartsV3ApiSpecs.NotFound>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    createCartRedirectUrl(cartId: CartsV3ApiSpecs.CreateCartRedirectUrlData['path']['cartId'], requestBody: CartsV3ApiSpecs.CreateCartRedirectUrlData['body']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<201, Required<CartsV3ApiSpecs.RedirectsCreateCartRedirectUrlResponse201>>>;
    getGlobalCartSettings(): Promise<RequestSuccessResponse<200, Required<CartsV3ApiSpecs.GlobalCartSettingsResponse>> | RequestErrorResponse<401, Required<CartsV3ApiSpecs.ErrorResponse>>>;
    updateGlobalCartSettings(requestBody: CartsV3ApiSpecs.UpdateGlobalCartSettingsData['body']): Promise<RequestErrorResponse<422, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.GlobalCartSettingsResponse>> | RequestErrorResponse<401, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.UpdateGlobalCartSettingsRequestBadRequestError>>>;
    getChannelCartSettings(channelId: CartsV3ApiSpecs.GetChannelCartSettingsData['path']['channel_id']): Promise<RequestErrorResponse<401, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.ChannelCartSettingsResponse>>>;
    updateChannelCartSettings(channelId: CartsV3ApiSpecs.UpdateChannelCartSettingsData['path']['channel_id'], requestBody: CartsV3ApiSpecs.UpdateChannelCartSettingsData['body']): Promise<RequestErrorResponse<422, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestErrorResponse<401, Required<CartsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CartsV3ApiSpecs.ChannelCartSettingsResponse>> | RequestErrorResponse<400, Required<CartsV3ApiSpecs.UpdateChannelCartSettingsRequestBadRequestError>>>;
}
