import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as CategoriesV3ApiSpecs from '../generated/categories-v3';
export * as CategoriesV3ApiSpecs from '../generated/categories-v3';
export declare class CategoriesV3Api {
    private readonly request;
    constructor(request: RequestService);
    getCategories(query?: CategoriesV3ApiSpecs.GetCategoriesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.CategoriesGetCategoriesResponse200>>>;
    createCategory(requestBody: CategoriesV3ApiSpecs.CreateCategoryData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.CategoriesCreateCategoryResponse200>> | RequestErrorResponse<409, Required<CategoriesV3ApiSpecs.CreateCategoryRequestConflictError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.CreateCategoryRequestUnprocessableEntityError>>>;
    deleteCategories(query?: CategoriesV3ApiSpecs.DeleteCategoriesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCategory(categoryId: CategoriesV3ApiSpecs.GetCategoryData['path']['category_id'], query?: CategoriesV3ApiSpecs.GetCategoryData['query']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.CategoriesGetCategoryResponse200>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.GetCategoryRequestNotFoundError>>>;
    updateCategory(categoryId: CategoriesV3ApiSpecs.UpdateCategoryData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategoryData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.CategoriesUpdateCategoryResponse200>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.UpdateCategoryRequestNotFoundError>> | RequestErrorResponse<409, Required<CategoriesV3ApiSpecs.UpdateCategoryRequestConflictError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.UpdateCategoryRequestUnprocessableEntityError>>>;
    deleteCategory(categoryId: CategoriesV3ApiSpecs.DeleteCategoryData['path']['category_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCategoriesMetafields(query?: CategoriesV3ApiSpecs.GetCategoriesMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponse>>>;
    createCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.CreateCategoriesMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.CreateCategoriesMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.UpdateCategoriesMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.UpdateCategoriesMetafieldsRequestBadRequestError>>>;
    deleteCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.DeleteCategoriesMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.DeleteCategoriesMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    createCategoryImage(categoryId: CategoriesV3ApiSpecs.CreateCategoryImageData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.CreateCategoryImageData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.ImagesCreateCategoryImageResponse200>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.CreateCategoryImageRequestBadRequestError>> | RequestErrorResponse<403, Required<CategoriesV3ApiSpecs._Error>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.CreateCategoryImageRequestNotFoundError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.CreateCategoryImageRequestUnprocessableEntityError>>>;
    deleteCategoryImage(categoryId: CategoriesV3ApiSpecs.DeleteCategoryImageData['path']['category_id']): Promise<RequestErrorResponse<403, Required<CategoriesV3ApiSpecs._Error>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.DeleteCategoryImageRequestNotFoundError>>>;
    getCategoryMetafields(categoryId: CategoriesV3ApiSpecs.GetCategoryMetafieldsData['path']['category_id'], query?: CategoriesV3ApiSpecs.GetCategoryMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetafieldsGetCategoryMetafieldsResponse200>>>;
    createCategoryMetafield(categoryId: CategoriesV3ApiSpecs.CreateCategoryMetafieldData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.CreateCategoryMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetafieldsCreateCategoryMetafieldResponse200>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.CreateCategoryMetafieldRequestBadRequestError>> | RequestErrorResponse<409, Required<CategoriesV3ApiSpecs.CreateCategoryMetafieldRequestConflictError>> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.CreateCategoryMetafieldRequestUnprocessableEntityError>>>;
    getCategoryMetafield(categoryId: CategoriesV3ApiSpecs.GetCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.GetCategoryMetafieldData['path']['metafield_id'], query?: CategoriesV3ApiSpecs.GetCategoryMetafieldData['query']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetafieldsGetCategoryMetafieldResponse200>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.GetCategoryMetafieldRequestNotFoundError>>>;
    updateCategoryMetafield(categoryId: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['path']['metafield_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.MetafieldsUpdateCategoryMetafieldResponse200>> | RequestErrorResponse<400, Required<CategoriesV3ApiSpecs.UpdateCategoryMetafieldRequestBadRequestError>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.UpdateCategoryMetafieldRequestNotFoundError>>>;
    deleteCategoryMetafield(categoryId: CategoriesV3ApiSpecs.DeleteCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.DeleteCategoryMetafieldData['path']['metafield_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.DeleteCategoryMetafieldRequestNotFoundError>>>;
    getCategorySortOrders(categoryId: CategoriesV3ApiSpecs.GetCategorySortOrdersData['path']['category_id'], query?: CategoriesV3ApiSpecs.GetCategorySortOrdersData['query']): Promise<RequestErrorResponse<403, Required<CategoriesV3ApiSpecs._Error>> | RequestSuccessResponse<200, Required<CategoriesV3ApiSpecs.SortOrderGetCategorySortOrdersResponse200>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.ErrorBase>>>;
    updateCategorySortOrders(categoryId: CategoriesV3ApiSpecs.UpdateCategorySortOrdersData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategorySortOrdersData['body'], query?: CategoriesV3ApiSpecs.UpdateCategorySortOrdersData['query']): Promise<RequestErrorResponse<403, Required<CategoriesV3ApiSpecs._Error>> | RequestErrorResponse<404, Required<CategoriesV3ApiSpecs.ErrorBase>> | RequestSuccessResponse<200, CategoriesV3ApiSpecs.ProductSortOrderFull[]> | RequestErrorResponse<422, Required<CategoriesV3ApiSpecs.ErrorBase>>>;
}
