import RequestService from '../helpers/request/request-service';
import * as CategoriesV3ApiSpecs from '../generated/categories-v3';
export default class CategoriesV3Api {
    private readonly request;
    constructor(request: RequestService);
    getCategories(query?: CategoriesV3ApiSpecs.GetCategoriesData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.GetCategoriesResponse, any>>;
    createCategory(requestBody: CategoriesV3ApiSpecs.CreateCategoryData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.CreateCategoryResponse, CategoriesV3ApiSpecs.CreateCategoryError>>;
    deleteCategories(query?: CategoriesV3ApiSpecs.DeleteCategoriesData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<any, any>>;
    getCategory(categoryId: CategoriesV3ApiSpecs.GetCategoryData['path']['category_id'], query?: CategoriesV3ApiSpecs.GetCategoryData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.GetCategoryResponse, CategoriesV3ApiSpecs.GetCategoryError>>;
    updateCategory(categoryId: CategoriesV3ApiSpecs.UpdateCategoryData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategoryData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.UpdateCategoryResponse, CategoriesV3ApiSpecs.UpdateCategoryError>>;
    deleteCategory(categoryId: CategoriesV3ApiSpecs.DeleteCategoryData['path']['category_id']): Promise<import("../helpers/request/request-service.type").RequestResponse<any, any>>;
    getCategoryMetafields(categoryId: CategoriesV3ApiSpecs.GetCategoryMetafieldsData['path']['category_id'], query?: CategoriesV3ApiSpecs.GetCategoryMetafieldsData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.GetCategoryMetafieldsResponse, any>>;
    createCategoryMetafield(categoryId: CategoriesV3ApiSpecs.CreateCategoryMetafieldData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.CreateCategoryMetafieldData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.CreateCategoryMetafieldResponse, CategoriesV3ApiSpecs.CreateCategoryMetafieldError>>;
    getCategoryMetafield(categoryId: CategoriesV3ApiSpecs.GetCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.GetCategoryMetafieldData['path']['metafield_id'], query?: CategoriesV3ApiSpecs.GetCategoryMetafieldData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.GetCategoryMetafieldResponse, CategoriesV3ApiSpecs.GetCategoryMetafieldError>>;
    updateCategoryMetafield(categoryId: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['path']['metafield_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategoryMetafieldData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.UpdateCategoryMetafieldResponse, CategoriesV3ApiSpecs.UpdateCategoryMetafieldError>>;
    deleteCategoryMetafield(categoryId: CategoriesV3ApiSpecs.DeleteCategoryMetafieldData['path']['category_id'], metafieldId: CategoriesV3ApiSpecs.DeleteCategoryMetafieldData['path']['metafield_id']): Promise<import("../helpers/request/request-service.type").RequestResponse<any, CategoriesV3ApiSpecs.DeleteCategoryMetafieldError>>;
    createCategoryImage(categoryId: CategoriesV3ApiSpecs.CreateCategoryImageData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.CreateCategoryImageData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.CreateCategoryImageResponse, CategoriesV3ApiSpecs.CreateCategoryImageError>>;
    deleteCategoryImage(categoryId: CategoriesV3ApiSpecs.DeleteCategoryImageData['path']['category_id']): Promise<import("../helpers/request/request-service.type").RequestResponse<any, CategoriesV3ApiSpecs.DeleteCategoryImageError>>;
    getCategorySortOrders(categoryId: CategoriesV3ApiSpecs.GetCategorySortOrdersData['path']['category_id']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.GetCategorySortOrdersResponse, CategoriesV3ApiSpecs.GetCategorySortOrdersError>>;
    updateCategorySortOrders(categoryId: CategoriesV3ApiSpecs.UpdateCategorySortOrdersData['path']['category_id'], requestBody: CategoriesV3ApiSpecs.UpdateCategorySortOrdersData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.UpdateCategorySortOrdersResponse, CategoriesV3ApiSpecs.UpdateCategorySortOrdersError>>;
    getCategoriesMetafields(query?: CategoriesV3ApiSpecs.GetCategoriesMetafieldsData['query']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.MetaFieldCollectionResponse, any>>;
    createCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.CreateCategoriesMetafieldsData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.MetaFieldCollectionResponse_POST_PUT, CategoriesV3ApiSpecs.CreateCategoriesMetafieldsError>>;
    updateCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.UpdateCategoriesMetafieldsData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.MetaFieldCollectionResponse_POST_PUT, CategoriesV3ApiSpecs.UpdateCategoriesMetafieldsError>>;
    deleteCategoriesMetafields(requestBody: CategoriesV3ApiSpecs.DeleteCategoriesMetafieldsData['body']): Promise<import("../helpers/request/request-service.type").RequestResponse<CategoriesV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess, CategoriesV3ApiSpecs.DeleteCategoriesMetafieldsError>>;
}
