import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as CustomersV3ApiSpecs from '../generated/customers-v3';
export * as CustomersV3ApiSpecs from '../generated/customers-v3';
export declare class CustomersV3Api {
    private readonly request;
    constructor(request: RequestService);
    getCustomers(query?: CustomersV3ApiSpecs.GetCustomersData['query']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.CustomersGetCustomersResponse200>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs._Error>>>;
    createCustomers(requestBody: CustomersV3ApiSpecs.CreateCustomersData['body']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.CustomersCreateCustomersResponse200>> | RequestErrorResponse<413, Required<unknown>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>>>;
    updateCustomers(requestBody: CustomersV3ApiSpecs.UpdateCustomersData['body']): Promise<RequestErrorResponse<413, Required<unknown>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.CustomersUpdateCustomersResponse200>>>;
    deleteCustomers(query?: CustomersV3ApiSpecs.DeleteCustomersData['query']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs._Error>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCustomersAddresses(query?: CustomersV3ApiSpecs.GetCustomersAddressesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AddressesGetCustomersAddressesResponse200>>>;
    createCustomersAddresses(requestBody: CustomersV3ApiSpecs.CreateCustomersAddressesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AddressesCreateCustomersAddressesResponse200>>>;
    updateCustomersAddresses(requestBody: CustomersV3ApiSpecs.UpdateCustomersAddressesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AddressesUpdateCustomersAddressesResponse200>>>;
    deleteCustomersAddresses(query?: CustomersV3ApiSpecs.DeleteCustomersAddressesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCustomersAttributeValues(query?: CustomersV3ApiSpecs.GetCustomersAttributeValuesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AttributeValuesGetCustomersAttributeValuesResponse200>>>;
    upsertCustomersAttributeValues(requestBody: CustomersV3ApiSpecs.UpsertCustomersAttributeValuesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AttributeValuesUpsertCustomersAttributeValuesResponse200>>>;
    deleteCustomersAttributeValues(query?: CustomersV3ApiSpecs.DeleteCustomersAttributeValuesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCustomersAttributes(query?: CustomersV3ApiSpecs.GetCustomersAttributesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AttributesGetCustomersAttributesResponse200>>>;
    createCustomersAttributes(requestBody: CustomersV3ApiSpecs.CreateCustomersAttributesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AttributesCreateCustomersAttributesResponse200>>>;
    updateCustomersAttributes(requestBody: CustomersV3ApiSpecs.UpdateCustomersAttributesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.AttributesUpdateCustomersAttributesResponse200>>>;
    deleteCustomersAttributes(query?: CustomersV3ApiSpecs.DeleteCustomersAttributesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCustomersSettingsChannel(channelId: CustomersV3ApiSpecs.GetCustomersSettingsChannelData['path']['channel_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.ChannelSettingsGetCustomersSettingsChannelResponse200>>>;
    updateCustomersSettingsChannel(channelId: CustomersV3ApiSpecs.UpdateCustomersSettingsChannelData['path']['channel_id'], requestBody: CustomersV3ApiSpecs.UpdateCustomersSettingsChannelData['body']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.ChannelSettingsUpdateCustomersSettingsChannelResponse200>>>;
    getCustomerConsent(customerId: CustomersV3ApiSpecs.GetCustomerConsentData['path']['customerId']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.ConsentFull>> | RequestErrorResponse<401, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestErrorResponse<403, Required<CustomersV3ApiSpecs.ErrorResponse>>>;
    updateCustomerConsent(customerId: CustomersV3ApiSpecs.UpdateCustomerConsentData['path']['customerId'], requestBody: CustomersV3ApiSpecs.UpdateCustomerConsentData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.ConsentFull>> | RequestErrorResponse<401, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestErrorResponse<403, Required<CustomersV3ApiSpecs.ErrorResponse>>>;
    getCustomersFormFieldValues(query?: CustomersV3ApiSpecs.GetCustomersFormFieldValuesData['query']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.FormFieldValuesGetCustomersFormFieldValuesResponse200>>>;
    updateCustomerFormFieldValues(requestBody: CustomersV3ApiSpecs.UpdateCustomerFormFieldValuesData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.FormFieldValuesUpdateCustomerFormFieldValuesResponse200>>>;
    getCustomersSettings(): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.GlobalSettingsGetCustomersSettingsResponse200>>>;
    updateCustomersSettings(requestBody: CustomersV3ApiSpecs.UpdateCustomersSettingsData['body']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.GlobalSettingsUpdateCustomersSettingsResponse200>>>;
    getCustomersMetafields(customerId: CustomersV3ApiSpecs.GetCustomersMetafieldsData['path']['customerId']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetafieldsGetCustomersMetafieldsResponse200>>>;
    createCustomerMetafields(customerId: CustomersV3ApiSpecs.CreateCustomerMetafieldsData['path']['customerId'], requestBody: CustomersV3ApiSpecs.CreateCustomerMetafieldsData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionPostPutResponses>> | RequestErrorResponse<400, Required<CustomersV3ApiSpecs.CreateCustomerMetafieldsRequestBadRequestError>> | RequestErrorResponse<409, Required<CustomersV3ApiSpecs.ErrorResponse>>>;
    getMetafieldsCustomerId(customerId: CustomersV3ApiSpecs.GetMetafieldsCustomerIdData['path']['customerId'], metafieldId: CustomersV3ApiSpecs.GetMetafieldsCustomerIdData['path']['metafieldId']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetafieldsGetMetafieldsCustomerIdResponse200>> | RequestErrorResponse<404, Required<CustomersV3ApiSpecs.NotFound>>>;
    updateCustomerMetafield(metafieldId: CustomersV3ApiSpecs.UpdateCustomerMetafieldData['path']['metafieldId'], customerId: CustomersV3ApiSpecs.UpdateCustomerMetafieldData['path']['customerId'], requestBody: CustomersV3ApiSpecs.UpdateCustomerMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionPostPutResponses>> | RequestErrorResponse<404, Required<CustomersV3ApiSpecs.NotFound>> | RequestErrorResponse<400, Required<CustomersV3ApiSpecs.UpdateCustomerMetafieldRequestBadRequestError>>>;
    deleteCustomerMetafieldsId(customerId: CustomersV3ApiSpecs.DeleteCustomerMetafieldsIdData['path']['customerId'], metafieldId: CustomersV3ApiSpecs.DeleteCustomerMetafieldsIdData['path']['metafieldId']): Promise<RequestErrorResponse<404, Required<CustomersV3ApiSpecs.NotFound>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getAllCustomersMetafields(query?: CustomersV3ApiSpecs.GetAllCustomersMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionResponse>>>;
    createCustomersMetafields(requestBody: CustomersV3ApiSpecs.CreateCustomersMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionPostPutResponses>> | RequestErrorResponse<400, Required<CustomersV3ApiSpecs.CreateCustomersMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateCustomersMetafields(requestBody: CustomersV3ApiSpecs.UpdateCustomersMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionPostPutResponses>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestErrorResponse<400, Required<CustomersV3ApiSpecs.UpdateCustomersMetafieldsRequestBadRequestError>>>;
    deleteCustomersMetafields(requestBody: CustomersV3ApiSpecs.DeleteCustomersMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<CustomersV3ApiSpecs.DeleteCustomersMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<CustomersV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    getCustomerStoredInstruments(customerId: CustomersV3ApiSpecs.GetCustomerStoredInstrumentsData['path']['customerId']): Promise<RequestErrorResponse<401, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestErrorResponse<403, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, CustomersV3ApiSpecs.CustomersCustomerIdStoredInstrumentsGetResponsesContentApplicationJsonSchemaItems[]>>;
    validateCustomerCredentials(requestBody: CustomersV3ApiSpecs.ValidateCustomerCredentialsData['body']): Promise<RequestErrorResponse<422, Required<CustomersV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<CustomersV3ApiSpecs.ValidateCustomerCredentialsResponseObject>> | RequestErrorResponse<429, Required<CustomersV3ApiSpecs.ErrorResponse>>>;
}
