import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as PriceListsV3ApiSpecs from '../generated/price-lists-v3';
export * as PriceListsV3ApiSpecs from '../generated/price-lists-v3';
export declare class PriceListsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getPriceLists(query?: PriceListsV3ApiSpecs.GetPriceListsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsGetPriceListsResponse200>>>;
    createPriceList(requestBody: PriceListsV3ApiSpecs.CreatePriceListData['body']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsCreatePriceListResponse200>> | RequestErrorResponse<409, Required<PriceListsV3ApiSpecs.CreatePriceListRequestConflictError>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.CreatePriceListRequestUnprocessableEntityError>>>;
    deletePriceLists(query?: PriceListsV3ApiSpecs.DeletePriceListsData['query']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<503, Required<PriceListsV3ApiSpecs.ServiceUnavailableError>>>;
    getPriceList(priceListId: PriceListsV3ApiSpecs.GetPriceListData['path']['price_list_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsGetPriceListResponse200>>>;
    updatePriceList(priceListId: PriceListsV3ApiSpecs.UpdatePriceListData['path']['price_list_id'], requestBody: PriceListsV3ApiSpecs.UpdatePriceListData['body']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsUpdatePriceListResponse200>> | RequestErrorResponse<404, Required<PriceListsV3ApiSpecs.UpdatePriceListRequestNotFoundError>> | RequestErrorResponse<409, Required<PriceListsV3ApiSpecs.UpdatePriceListRequestConflictError>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.UpdatePriceListRequestUnprocessableEntityError>>>;
    deletePriceList(priceListId: PriceListsV3ApiSpecs.DeletePriceListData['path']['price_list_id']): Promise<RequestErrorResponse<503, Required<PriceListsV3ApiSpecs.ServiceUnavailableError>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getListOfPriceListAssignments(query?: PriceListsV3ApiSpecs.GetListOfPriceListAssignmentsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.AssignmentsForGetResponse>>>;
    createPriceListAssignments(requestBody: PriceListsV3ApiSpecs.CreatePriceListAssignmentsData['body']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsAssignmentsCreatePriceListAssignmentsResponse200>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.PriceListAssignmentsBatchErrorResponse>>>;
    deletePriceListAssignments(query?: PriceListsV3ApiSpecs.DeletePriceListAssignmentsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    upsertPriceListAssignment(priceListId: PriceListsV3ApiSpecs.UpsertPriceListAssignmentData['path']['price_list_id'], requestBody: PriceListsV3ApiSpecs.UpsertPriceListAssignmentData['body']): Promise<RequestErrorResponse<404, Required<unknown>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.AssignmentForPutResponse>>>;
    createPriceListsRecords(requestBody: PriceListsV3ApiSpecs.CreatePriceListsRecordsData['body']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.SuccessBatchResponse>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.PriceRecordBatchErrorResponse>>>;
    upsertPriceListsRecords(requestBody: PriceListsV3ApiSpecs.UpsertPriceListsRecordsData['body']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.SuccessBatchResponse>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.PriceRecordBatchErrorResponse>>>;
    getPriceListRecords(priceListId: PriceListsV3ApiSpecs.GetPriceListRecordsData['path']['price_list_id'], query?: PriceListsV3ApiSpecs.GetPriceListRecordsData['query']): Promise<RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsGetPriceListRecordsResponse200>> | RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>>>;
    createPriceListRecords(priceListId: PriceListsV3ApiSpecs.CreatePriceListRecordsData['path']['price_list_id'], requestBody: PriceListsV3ApiSpecs.CreatePriceListRecordsData['body']): Promise<RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsCreatePriceListRecordsResponse200>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.CreatePriceListRecordsRequestUnprocessableEntityError>>>;
    upsertPriceListRecords(priceListId: PriceListsV3ApiSpecs.UpsertPriceListRecordsData['path']['price_list_id'], requestBody: PriceListsV3ApiSpecs.UpsertPriceListRecordsData['body']): Promise<RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsUpsertPriceListRecordsResponse200>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.UpsertPriceListRecordsRequestUnprocessableEntityError>>>;
    deletePriceListRecords(priceListId: PriceListsV3ApiSpecs.DeletePriceListRecordsData['path']['price_list_id'], query?: PriceListsV3ApiSpecs.DeletePriceListRecordsData['query']): Promise<RequestErrorResponse<503, Required<PriceListsV3ApiSpecs.ServiceUnavailableError>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getPriceListRecordsByVariantId(priceListId: PriceListsV3ApiSpecs.GetPriceListRecordsByVariantIdData['path']['price_list_id'], variantId: PriceListsV3ApiSpecs.GetPriceListRecordsByVariantIdData['path']['variant_id'], query?: PriceListsV3ApiSpecs.GetPriceListRecordsByVariantIdData['query']): Promise<RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsGetPriceListRecordsByVariantIdResponse200>>>;
    getPriceListRecord(priceListId: PriceListsV3ApiSpecs.GetPriceListRecordData['path']['price_list_id'], variantId: PriceListsV3ApiSpecs.GetPriceListRecordData['path']['variant_id'], currencyCode: PriceListsV3ApiSpecs.GetPriceListRecordData['path']['currency_code'], query?: PriceListsV3ApiSpecs.GetPriceListRecordData['query']): Promise<RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsGetPriceListRecordResponse200>>>;
    setPriceListRecord(priceListId: PriceListsV3ApiSpecs.SetPriceListRecordData['path']['price_list_id'], variantId: PriceListsV3ApiSpecs.SetPriceListRecordData['path']['variant_id'], currencyCode: PriceListsV3ApiSpecs.SetPriceListRecordData['path']['currency_code'], requestBody: PriceListsV3ApiSpecs.SetPriceListRecordData['body']): Promise<RequestErrorResponse<429, Required<PriceListsV3ApiSpecs.ErrorResponse>> | RequestSuccessResponse<200, Required<PriceListsV3ApiSpecs.PriceListsRecordsSetPriceListRecordResponse200>> | RequestErrorResponse<404, Required<PriceListsV3ApiSpecs.SetPriceListRecordRequestNotFoundError>> | RequestErrorResponse<409, Required<PriceListsV3ApiSpecs.SetPriceListRecordRequestConflictError>> | RequestErrorResponse<422, Required<PriceListsV3ApiSpecs.SetPriceListRecordRequestUnprocessableEntityError>>>;
    deletePriceListRecord(priceListId: PriceListsV3ApiSpecs.DeletePriceListRecordData['path']['price_list_id'], variantId: PriceListsV3ApiSpecs.DeletePriceListRecordData['path']['variant_id'], currencyCode: PriceListsV3ApiSpecs.DeletePriceListRecordData['path']['currency_code']): Promise<RequestErrorResponse<503, Required<PriceListsV3ApiSpecs.ServiceUnavailableError>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
}
