import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as ProductsV3ApiSpecs from '../generated/products-v3';
export * as ProductsV3ApiSpecs from '../generated/products-v3';
export declare class ProductsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getProducts(query?: ProductsV3ApiSpecs.GetProductsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ProductsGetProductsResponse200>>>;
    createProduct(requestBody: ProductsV3ApiSpecs.CreateProductData['body'], query?: ProductsV3ApiSpecs.CreateProductData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ProductsCreateProductResponse200>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.CreateProductRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.CreateProductRequestUnprocessableEntityError>>>;
    updateProducts(requestBody: ProductsV3ApiSpecs.UpdateProductsData['body'], query?: ProductsV3ApiSpecs.UpdateProductsData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ProductsUpdateProductsResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductsRequestNotFoundError>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.ErrorResponse409>> | RequestErrorResponse<413, Required<ProductsV3ApiSpecs.ErrorBase>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.ErrorResponse422>>>;
    deleteProducts(query?: ProductsV3ApiSpecs.DeleteProductsData['query']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.DeleteProductsRequestUnprocessableEntityError>>>;
    getProduct(productId: ProductsV3ApiSpecs.GetProductData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ProductsGetProductResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductRequestNotFoundError>>>;
    updateProduct(productId: ProductsV3ApiSpecs.UpdateProductData['path']['product_id'], requestBody: ProductsV3ApiSpecs.UpdateProductData['body'], query?: ProductsV3ApiSpecs.UpdateProductData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ProductsUpdateProductResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductRequestNotFoundError>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.UpdateProductRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.UpdateProductRequestUnprocessableEntityError>>>;
    deleteProduct(productId: ProductsV3ApiSpecs.DeleteProductData['path']['product_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductsMetafields(query?: ProductsV3ApiSpecs.GetProductsMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponse>>>;
    createProductsMetafields(requestBody: ProductsV3ApiSpecs.CreateProductsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.CreateProductsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateProductsMetafields(requestBody: ProductsV3ApiSpecs.UpdateProductsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.UpdateProductsMetafieldsRequestBadRequestError>>>;
    deleteProductsMetafields(requestBody: ProductsV3ApiSpecs.DeleteProductsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.DeleteProductsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    getAllBulkPricingRules(productId: ProductsV3ApiSpecs.GetAllBulkPricingRulesData['path']['product_id'], query?: ProductsV3ApiSpecs.GetAllBulkPricingRulesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.BulkPricingRulesGetAllBulkPricingRulesResponse200>>>;
    createBulkPricingRule(productId: ProductsV3ApiSpecs.CreateBulkPricingRuleData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateBulkPricingRuleData['body']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.BulkPricingRulesCreateBulkPricingRuleResponse200>>>;
    getBulkPricingRule(productId: ProductsV3ApiSpecs.GetBulkPricingRuleData['path']['product_id'], bulkPricingRuleId: ProductsV3ApiSpecs.GetBulkPricingRuleData['path']['bulk_pricing_rule_id'], query?: ProductsV3ApiSpecs.GetBulkPricingRuleData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.BulkPricingRulesGetBulkPricingRuleResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetBulkPricingRuleRequestNotFoundError>>>;
    updateBulkPricingRule(productId: ProductsV3ApiSpecs.UpdateBulkPricingRuleData['path']['product_id'], bulkPricingRuleId: ProductsV3ApiSpecs.UpdateBulkPricingRuleData['path']['bulk_pricing_rule_id'], requestBody: ProductsV3ApiSpecs.UpdateBulkPricingRuleData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.BulkPricingRulesUpdateBulkPricingRuleResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateBulkPricingRuleRequestNotFoundError>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.UpdateBulkPricingRuleRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.UpdateBulkPricingRuleRequestUnprocessableEntityError>>>;
    deleteBulkPricingRule(productId: ProductsV3ApiSpecs.DeleteBulkPricingRuleData['path']['product_id'], bulkPricingRuleId: ProductsV3ApiSpecs.DeleteBulkPricingRuleData['path']['bulk_pricing_rule_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.DeleteBulkPricingRuleRequestNotFoundError>>>;
    getProductsCategoryAssignments(query?: ProductsV3ApiSpecs.GetProductsCategoryAssignmentsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.CategoryAssignmentsGetProductsCategoryAssignmentsResponse200>>>;
    createProductsCategoryAssignments(requestBody: ProductsV3ApiSpecs.CreateProductsCategoryAssignmentsData['body']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.Beta5ErrorResponse>>>;
    deleteProductsCategoryAssignments(query?: ProductsV3ApiSpecs.DeleteProductsCategoryAssignmentsData['query']): Promise<RequestErrorResponse<422, Required<ProductsV3ApiSpecs.Beta5ErrorResponse>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductsChannelAssignments(query?: ProductsV3ApiSpecs.GetProductsChannelAssignmentsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ChannelAssignmentsGetProductsChannelAssignmentsResponse200>>>;
    createProductsChannelAssignments(requestBody: ProductsV3ApiSpecs.CreateProductsChannelAssignmentsData['body']): Promise<RequestErrorResponse<422, Required<ProductsV3ApiSpecs.Beta5ErrorResponse>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    deleteProductsChannelAssignments(query?: ProductsV3ApiSpecs.DeleteProductsChannelAssignmentsData['query']): Promise<RequestErrorResponse<422, Required<ProductsV3ApiSpecs.Beta5ErrorResponse>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductComplexRules(productId: ProductsV3ApiSpecs.GetProductComplexRulesData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductComplexRulesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ComplexRulesGetProductComplexRulesResponse200>>>;
    createProductComplexRule(productId: ProductsV3ApiSpecs.CreateProductComplexRuleData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductComplexRuleData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ComplexRulesCreateProductComplexRuleResponse200>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.CreateProductComplexRuleRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.CreateProductComplexRuleRequestUnprocessableEntityError>>>;
    getProductComplexRule(productId: ProductsV3ApiSpecs.GetProductComplexRuleData['path']['product_id'], complexRuleId: ProductsV3ApiSpecs.GetProductComplexRuleData['path']['complex_rule_id'], query?: ProductsV3ApiSpecs.GetProductComplexRuleData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ComplexRulesGetProductComplexRuleResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductComplexRuleRequestNotFoundError>>>;
    updateProductComplexRule(productId: ProductsV3ApiSpecs.UpdateProductComplexRuleData['path']['product_id'], complexRuleId: ProductsV3ApiSpecs.UpdateProductComplexRuleData['path']['complex_rule_id'], requestBody: ProductsV3ApiSpecs.UpdateProductComplexRuleData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ComplexRulesUpdateProductComplexRuleResponse200>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.UpdateProductComplexRuleRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.UpdateProductComplexRuleRequestUnprocessableEntityError>>>;
    deleteProductComplexRule(productId: ProductsV3ApiSpecs.DeleteProductComplexRuleData['path']['product_id'], complexRuleId: ProductsV3ApiSpecs.DeleteProductComplexRuleData['path']['complex_rule_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductCustomFields(productId: ProductsV3ApiSpecs.GetProductCustomFieldsData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductCustomFieldsData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.CustomFieldsGetProductCustomFieldsResponse200>> | RequestErrorResponse<403, Required<ProductsV3ApiSpecs.GeneralErrorWithErrors>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GeneralError>> | RequestErrorResponse<405, Required<ProductsV3ApiSpecs.MethodNotAllowedError>>>;
    createProductCustomField(productId: ProductsV3ApiSpecs.CreateProductCustomFieldData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductCustomFieldData['body']): Promise<RequestErrorResponse<403, Required<ProductsV3ApiSpecs.GeneralErrorWithErrors>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GeneralError>> | RequestErrorResponse<405, Required<ProductsV3ApiSpecs.MethodNotAllowedError>> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.CustomFieldsCreateProductCustomFieldResponse200>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.GeneralError>>>;
    getProductCustomField(productId: ProductsV3ApiSpecs.GetProductCustomFieldData['path']['product_id'], customFieldId: ProductsV3ApiSpecs.GetProductCustomFieldData['path']['custom_field_id'], query?: ProductsV3ApiSpecs.GetProductCustomFieldData['query']): Promise<RequestErrorResponse<403, Required<ProductsV3ApiSpecs.GeneralErrorWithErrors>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GeneralError>> | RequestErrorResponse<405, Required<ProductsV3ApiSpecs.MethodNotAllowedError>> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.CustomFieldsGetProductCustomFieldResponse200>>>;
    updateProductCustomField(productId: ProductsV3ApiSpecs.UpdateProductCustomFieldData['path']['product_id'], customFieldId: ProductsV3ApiSpecs.UpdateProductCustomFieldData['path']['custom_field_id'], requestBody: ProductsV3ApiSpecs.UpdateProductCustomFieldData['body']): Promise<RequestErrorResponse<403, Required<ProductsV3ApiSpecs.GeneralErrorWithErrors>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GeneralError>> | RequestErrorResponse<405, Required<ProductsV3ApiSpecs.MethodNotAllowedError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.GeneralError>> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.CustomFieldsUpdateProductCustomFieldResponse200>>>;
    deleteProductCustomField(productId: ProductsV3ApiSpecs.DeleteProductCustomFieldData['path']['product_id'], customFieldId: ProductsV3ApiSpecs.DeleteProductCustomFieldData['path']['custom_field_id']): Promise<RequestErrorResponse<403, Required<ProductsV3ApiSpecs.GeneralErrorWithErrors>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GeneralError>> | RequestErrorResponse<405, Required<ProductsV3ApiSpecs.MethodNotAllowedError>> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductImages(productId: ProductsV3ApiSpecs.GetProductImagesData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductImagesData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ImagesGetProductImagesResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductImagesRequestNotFoundError>>>;
    createProductImage(productId: ProductsV3ApiSpecs.CreateProductImageData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductImageData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ImagesCreateProductImageResponse200>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.CreateProductImageRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.CreateProductImageRequestNotFoundError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.CreateProductImageRequestUnprocessableEntityError>>>;
    getProductImage(productId: ProductsV3ApiSpecs.GetProductImageData['path']['product_id'], imageId: ProductsV3ApiSpecs.GetProductImageData['path']['image_id'], query?: ProductsV3ApiSpecs.GetProductImageData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ImagesGetProductImageResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductImageRequestNotFoundError>>>;
    updateProductImage(productId: ProductsV3ApiSpecs.UpdateProductImageData['path']['product_id'], imageId: ProductsV3ApiSpecs.UpdateProductImageData['path']['image_id'], requestBody: ProductsV3ApiSpecs.UpdateProductImageData['body']): Promise<RequestErrorResponse<422, Required<ProductsV3ApiSpecs.ErrorResponse422>> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ImagesUpdateProductImageResponse200>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.UpdateProductImageRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductImageRequestNotFoundError>>>;
    deleteProductImage(productId: ProductsV3ApiSpecs.DeleteProductImageData['path']['product_id'], imageId: ProductsV3ApiSpecs.DeleteProductImageData['path']['image_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductMetafields(productId: ProductsV3ApiSpecs.GetProductMetafieldsData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetafieldsGetProductMetafieldsResponse200>>>;
    createProductMetafield(productId: ProductsV3ApiSpecs.CreateProductMetafieldData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetafieldsCreateProductMetafieldResponse200>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.CreateProductMetafieldRequestBadRequestError>> | RequestErrorResponse<409, Required<ProductsV3ApiSpecs.CreateProductMetafieldRequestConflictError>> | RequestErrorResponse<422, Required<ProductsV3ApiSpecs.CreateProductMetafieldRequestUnprocessableEntityError>>>;
    getProductMetafield(productId: ProductsV3ApiSpecs.GetProductMetafieldData['path']['product_id'], metafieldId: ProductsV3ApiSpecs.GetProductMetafieldData['path']['metafield_id'], query?: ProductsV3ApiSpecs.GetProductMetafieldData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetafieldsGetProductMetafieldResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductMetafieldRequestNotFoundError>>>;
    updateProductMetafield(productId: ProductsV3ApiSpecs.UpdateProductMetafieldData['path']['product_id'], metafieldId: ProductsV3ApiSpecs.UpdateProductMetafieldData['path']['metafield_id'], requestBody: ProductsV3ApiSpecs.UpdateProductMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.MetafieldsUpdateProductMetafieldResponse200>> | RequestErrorResponse<400, Required<ProductsV3ApiSpecs.UpdateProductMetafieldRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductMetafieldRequestNotFoundError>>>;
    deleteProductMetafield(productId: ProductsV3ApiSpecs.DeleteProductMetafieldData['path']['product_id'], metafieldId: ProductsV3ApiSpecs.DeleteProductMetafieldData['path']['metafield_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.DeleteProductMetafieldRequestNotFoundError>>>;
    getProductReviews(productId: ProductsV3ApiSpecs.GetProductReviewsData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductReviewsData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ReviewsGetProductReviewsResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductReviewsRequestNotFoundError>>>;
    createProductReview(productId: ProductsV3ApiSpecs.CreateProductReviewData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductReviewData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ReviewsCreateProductReviewResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.CreateProductReviewRequestNotFoundError>>>;
    getProductReview(productId: ProductsV3ApiSpecs.GetProductReviewData['path']['product_id'], reviewId: ProductsV3ApiSpecs.GetProductReviewData['path']['review_id'], query?: ProductsV3ApiSpecs.GetProductReviewData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ReviewsGetProductReviewResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductReviewRequestNotFoundError>>>;
    updateProductReview(productId: ProductsV3ApiSpecs.UpdateProductReviewData['path']['product_id'], reviewId: ProductsV3ApiSpecs.UpdateProductReviewData['path']['review_id'], requestBody: ProductsV3ApiSpecs.UpdateProductReviewData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.ReviewsUpdateProductReviewResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductReviewRequestNotFoundError>>>;
    deleteProductReview(productId: ProductsV3ApiSpecs.DeleteProductReviewData['path']['product_id'], reviewId: ProductsV3ApiSpecs.DeleteProductReviewData['path']['review_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getCatalogSummary(): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.SummaryGetCatalogSummaryResponse200>>>;
    getProductVideos(productId: ProductsV3ApiSpecs.GetProductVideosData['path']['product_id'], query?: ProductsV3ApiSpecs.GetProductVideosData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.VideosGetProductVideosResponse200>>>;
    createProductVideo(productId: ProductsV3ApiSpecs.CreateProductVideoData['path']['product_id'], requestBody: ProductsV3ApiSpecs.CreateProductVideoData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.VideosCreateProductVideoResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.CreateProductVideoRequestNotFoundError>>>;
    getProductVideo(productId: ProductsV3ApiSpecs.GetProductVideoData['path']['product_id'], id: ProductsV3ApiSpecs.GetProductVideoData['path']['id'], query?: ProductsV3ApiSpecs.GetProductVideoData['query']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.VideosGetProductVideoResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.GetProductVideoRequestNotFoundError>>>;
    updateProductVideo(productId: ProductsV3ApiSpecs.UpdateProductVideoData['path']['product_id'], id: ProductsV3ApiSpecs.UpdateProductVideoData['path']['id'], requestBody: ProductsV3ApiSpecs.UpdateProductVideoData['body']): Promise<RequestSuccessResponse<200, Required<ProductsV3ApiSpecs.VideosUpdateProductVideoResponse200>> | RequestErrorResponse<404, Required<ProductsV3ApiSpecs.UpdateProductVideoRequestNotFoundError>>>;
    deleteProductVideo(productId: ProductsV3ApiSpecs.DeleteProductVideoData['path']['product_id'], id: ProductsV3ApiSpecs.DeleteProductVideoData['path']['id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
}
