import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as ProductVariantOptionsV3ApiSpecs from '../generated/product-variant-options-v3';
export * as ProductVariantOptionsV3ApiSpecs from '../generated/product-variant-options-v3';
export declare class ProductVariantOptionsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getProductVariantOptions(productId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionsData['path']['product_id'], query?: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionsData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ProductVariantOptionsGetProductVariantOptionsResponse200>> | RequestErrorResponse<404, Required<ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionsRequestNotFoundError>>>;
    createProductVariantOption(productId: ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionData['path']['product_id'], requestBody: ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ProductVariantOptionsCreateProductVariantOptionResponse200>> | RequestErrorResponse<409, Required<ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionRequestConflictError>> | RequestErrorResponse<422, Required<ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionRequestUnprocessableEntityError>>>;
    getProductVariantOption(productId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionData['path']['option_id'], query?: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ProductVariantOptionsGetProductVariantOptionResponse200>> | RequestErrorResponse<404, Required<ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionRequestNotFoundError>>>;
    updateProductVariantOption(productId: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionData['path']['option_id'], requestBody: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ProductVariantOptionsUpdateProductVariantOptionResponse200>> | RequestErrorResponse<409, Required<ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionRequestConflictError>> | RequestErrorResponse<422, Required<ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionRequestUnprocessableEntityError>>>;
    deleteProductVariantOption(productId: ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionData['path']['option_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getProductVariantOptionValues(productId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValuesData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValuesData['path']['option_id'], query?: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValuesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ValuesGetProductVariantOptionValuesResponse200>>>;
    createProductVariantOptionValue(productId: ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionValueData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionValueData['path']['option_id'], requestBody: ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionValueData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ValuesCreateProductVariantOptionValueResponse200>> | RequestErrorResponse<422, Required<ProductVariantOptionsV3ApiSpecs.CreateProductVariantOptionValueRequestUnprocessableEntityError>>>;
    getProductVariantOptionValue(productId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValueData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValueData['path']['option_id'], valueId: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValueData['path']['value_id'], query?: ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValueData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ValuesGetProductVariantOptionValueResponse200>> | RequestErrorResponse<404, Required<ProductVariantOptionsV3ApiSpecs.GetProductVariantOptionValueRequestNotFoundError>>>;
    updateProductVariantOptionValue(productId: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionValueData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionValueData['path']['option_id'], valueId: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionValueData['path']['value_id'], requestBody: ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionValueData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantOptionsV3ApiSpecs.ValuesUpdateProductVariantOptionValueResponse200>> | RequestErrorResponse<422, Required<ProductVariantOptionsV3ApiSpecs.UpdateProductVariantOptionValueRequestUnprocessableEntityError>>>;
    deleteProductVariantOptionValue(productId: ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionValueData['path']['product_id'], optionId: ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionValueData['path']['option_id'], valueId: ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionValueData['path']['value_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<422, Required<ProductVariantOptionsV3ApiSpecs.DeleteProductVariantOptionValueRequestUnprocessableEntityError>>>;
}
