import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as ProductVariantsV3ApiSpecs from '../generated/product-variants-v3';
export * as ProductVariantsV3ApiSpecs from '../generated/product-variants-v3';
export declare class ProductVariantsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getProductVariants(productId: ProductVariantsV3ApiSpecs.GetProductVariantsData['path']['product_id'], query?: ProductVariantsV3ApiSpecs.GetProductVariantsData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.ProductVariantsGetProductVariantsResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.GetProductVariantsRequestNotFoundError>>>;
    createProductVariant(productId: ProductVariantsV3ApiSpecs.CreateProductVariantData['path']['product_id'], requestBody: ProductVariantsV3ApiSpecs.CreateProductVariantData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.ProductVariantsCreateProductVariantResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.CreateProductVariantRequestNotFoundError>>>;
    getProductVariant(productId: ProductVariantsV3ApiSpecs.GetProductVariantData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.GetProductVariantData['path']['variant_id'], query?: ProductVariantsV3ApiSpecs.GetProductVariantData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.ProductVariantsGetProductVariantResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.GetProductVariantRequestNotFoundError>>>;
    updateProductVariant(productId: ProductVariantsV3ApiSpecs.UpdateProductVariantData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.UpdateProductVariantData['path']['variant_id'], requestBody: ProductVariantsV3ApiSpecs.UpdateProductVariantData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.ProductVariantsUpdateProductVariantResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.UpdateProductVariantRequestNotFoundError>>>;
    deleteProductVariant(productId: ProductVariantsV3ApiSpecs.DeleteProductVariantData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.DeleteProductVariantData['path']['variant_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    getVariantsMetafields(query?: ProductVariantsV3ApiSpecs.GetVariantsMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponse>>>;
    createVariantsMetafields(requestBody: ProductVariantsV3ApiSpecs.CreateVariantsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.CreateVariantsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>>>;
    updateVariantsMetafields(requestBody: ProductVariantsV3ApiSpecs.UpdateVariantsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponsePostPut>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessPostPut>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.UpdateVariantsMetafieldsRequestBadRequestError>>>;
    deleteVariantsMetafields(requestBody: ProductVariantsV3ApiSpecs.DeleteVariantsMetafieldsData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionDeleteResponseSuccess>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.DeleteVariantsMetafieldsRequestBadRequestError>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.MetaFieldCollectionResponsePartialSuccessDelete>>>;
    createProductVariantImage(productId: ProductVariantsV3ApiSpecs.CreateProductVariantImageData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.CreateProductVariantImageData['path']['variant_id'], requestBody: ProductVariantsV3ApiSpecs.CreateProductVariantImageData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.ImagesCreateProductVariantImageResponse200>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.CreateProductVariantImageRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.CreateProductVariantImageRequestNotFoundError>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.CreateProductVariantImageRequestUnprocessableEntityError>> | RequestErrorResponse<500, Required<ProductVariantsV3ApiSpecs.CreateProductVariantImageRequestInternalServerError>>>;
    getProductVariantMetafields(productId: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldsData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldsData['path']['variant_id'], query?: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldsData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetafieldsGetProductVariantMetafieldsResponse200>>>;
    createProductVariantMetafield(productId: ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldData['path']['variant_id'], requestBody: ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetafieldsCreateProductVariantMetafieldResponse200>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldRequestBadRequestError>> | RequestErrorResponse<409, Required<ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldRequestConflictError>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.CreateProductVariantMetafieldRequestUnprocessableEntityError>>>;
    getProductVariantMetafield(productId: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldData['path']['variant_id'], metafieldId: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldData['path']['metafield_id'], query?: ProductVariantsV3ApiSpecs.GetProductVariantMetafieldData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetafieldsGetProductVariantMetafieldResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.GetProductVariantMetafieldRequestNotFoundError>>>;
    updateProductVariantMetafield(productId: ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldData['path']['variant_id'], metafieldId: ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldData['path']['metafield_id'], requestBody: ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.MetafieldsUpdateProductVariantMetafieldResponse200>> | RequestErrorResponse<400, Required<ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.UpdateProductVariantMetafieldRequestNotFoundError>>>;
    deleteProductVariantMetafield(productId: ProductVariantsV3ApiSpecs.DeleteProductVariantMetafieldData['path']['product_id'], variantId: ProductVariantsV3ApiSpecs.DeleteProductVariantMetafieldData['path']['variant_id'], metafieldId: ProductVariantsV3ApiSpecs.DeleteProductVariantMetafieldData['path']['metafield_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.DeleteProductVariantMetafieldRequestNotFoundError>>>;
    getVariants(query?: ProductVariantsV3ApiSpecs.GetVariantsData['query']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.VariantsBatchGetVariantsResponse200>> | RequestErrorResponse<404, Required<ProductVariantsV3ApiSpecs.GetVariantsRequestNotFoundError>>>;
    updateVariantsBatch(requestBody: ProductVariantsV3ApiSpecs.UpdateVariantsBatchData['body']): Promise<RequestSuccessResponse<200, Required<ProductVariantsV3ApiSpecs.VariantsBatchUpdateVariantsBatchResponse200>> | RequestErrorResponse<422, Required<ProductVariantsV3ApiSpecs.UpdateVariantsBatchRequestUnprocessableEntityError>>>;
}
