import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as ProductModifiersV3ApiSpecs from '../generated/product-modifiers-v3';
export * as ProductModifiersV3ApiSpecs from '../generated/product-modifiers-v3';
export declare class ProductModifiersV3Api {
    private readonly request;
    constructor(request: RequestService);
    getProductModifiers(productId: ProductModifiersV3ApiSpecs.GetProductModifiersData['path']['product_id'], query?: ProductModifiersV3ApiSpecs.GetProductModifiersData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ProductModifiersGetProductModifiersResponse200>>>;
    createProductModifier(productId: ProductModifiersV3ApiSpecs.CreateProductModifierData['path']['product_id'], requestBody: ProductModifiersV3ApiSpecs.CreateProductModifierData['body']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ProductModifiersCreateProductModifierResponse200>> | RequestErrorResponse<409, Required<ProductModifiersV3ApiSpecs.CreateProductModifierRequestConflictError>> | RequestErrorResponse<422, Required<ProductModifiersV3ApiSpecs.CreateProductModifierRequestUnprocessableEntityError>>>;
    getProductModifier(productId: ProductModifiersV3ApiSpecs.GetProductModifierData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.GetProductModifierData['path']['modifier_id'], query?: ProductModifiersV3ApiSpecs.GetProductModifierData['query']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ProductModifiersGetProductModifierResponse200>> | RequestErrorResponse<404, Required<ProductModifiersV3ApiSpecs.GetProductModifierRequestNotFoundError>>>;
    updateProductModifier(productId: ProductModifiersV3ApiSpecs.UpdateProductModifierData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.UpdateProductModifierData['path']['modifier_id'], requestBody: ProductModifiersV3ApiSpecs.UpdateProductModifierData['body']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ProductModifiersUpdateProductModifierResponse200>> | RequestErrorResponse<409, Required<ProductModifiersV3ApiSpecs.UpdateProductModifierRequestConflictError>> | RequestErrorResponse<422, Required<ProductModifiersV3ApiSpecs.UpdateProductModifierRequestUnprocessableEntityError>>>;
    deleteProductModifier(productId: ProductModifiersV3ApiSpecs.DeleteProductModifierData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.DeleteProductModifierData['path']['modifier_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
    createProductModifierImage(productId: ProductModifiersV3ApiSpecs.CreateProductModifierImageData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.CreateProductModifierImageData['path']['modifier_id'], valueId: ProductModifiersV3ApiSpecs.CreateProductModifierImageData['path']['value_id'], requestBody: ProductModifiersV3ApiSpecs.CreateProductModifierImageData['body']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ImagesCreateProductModifierImageResponse200>> | RequestErrorResponse<400, Required<ProductModifiersV3ApiSpecs.CreateProductModifierImageRequestBadRequestError>> | RequestErrorResponse<404, Required<ProductModifiersV3ApiSpecs.CreateProductModifierImageRequestNotFoundError>> | RequestErrorResponse<422, Required<ProductModifiersV3ApiSpecs.CreateProductModifierImageRequestUnprocessableEntityError>>>;
    getProductModifierValues(productId: ProductModifiersV3ApiSpecs.GetProductModifierValuesData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.GetProductModifierValuesData['path']['modifier_id'], query?: ProductModifiersV3ApiSpecs.GetProductModifierValuesData['query']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ValuesGetProductModifierValuesResponse200>>>;
    createProductModifierValue(productId: ProductModifiersV3ApiSpecs.CreateProductModifierValueData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.CreateProductModifierValueData['path']['modifier_id'], requestBody: ProductModifiersV3ApiSpecs.CreateProductModifierValueData['body']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ValuesCreateProductModifierValueResponse200>> | RequestErrorResponse<422, Required<ProductModifiersV3ApiSpecs.CreateProductModifierValueRequestUnprocessableEntityError>>>;
    getProductModifierValue(productId: ProductModifiersV3ApiSpecs.GetProductModifierValueData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.GetProductModifierValueData['path']['modifier_id'], valueId: ProductModifiersV3ApiSpecs.GetProductModifierValueData['path']['value_id'], query?: ProductModifiersV3ApiSpecs.GetProductModifierValueData['query']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ValuesGetProductModifierValueResponse200>> | RequestErrorResponse<404, Required<ProductModifiersV3ApiSpecs.GetProductModifierValueRequestNotFoundError>>>;
    updateProductModifierValue(productId: ProductModifiersV3ApiSpecs.UpdateProductModifierValueData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.UpdateProductModifierValueData['path']['modifier_id'], valueId: ProductModifiersV3ApiSpecs.UpdateProductModifierValueData['path']['value_id'], requestBody: ProductModifiersV3ApiSpecs.UpdateProductModifierValueData['body']): Promise<RequestSuccessResponse<200, Required<ProductModifiersV3ApiSpecs.ValuesUpdateProductModifierValueResponse200>> | RequestErrorResponse<422, Required<ProductModifiersV3ApiSpecs.UpdateProductModifierValueRequestUnprocessableEntityError>>>;
    deleteProductModifierValue(productId: ProductModifiersV3ApiSpecs.DeleteProductModifierValueData['path']['product_id'], modifierId: ProductModifiersV3ApiSpecs.DeleteProductModifierValueData['path']['modifier_id'], valueId: ProductModifiersV3ApiSpecs.DeleteProductModifierValueData['path']['value_id']): Promise<RequestErrorResponse<400, void> | RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>>>;
}
