import RequestService from '../helpers/request/request-service';
import type { RequestSuccessResponse, RequestErrorResponse } from '../helpers/request/request-service.types';
import * as WishlistsV3ApiSpecs from '../generated/wishlists-v3';
export * as WishlistsV3ApiSpecs from '../generated/wishlists-v3';
export declare class WishlistsV3Api {
    private readonly request;
    constructor(request: RequestService);
    getWishlists(query?: WishlistsV3ApiSpecs.GetWishlistsData['query']): Promise<RequestSuccessResponse<200, Required<WishlistsV3ApiSpecs.WishlistsGetWishlistsResponse200>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.GetWishlistsRequestUnauthorizedError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.GetWishlistsRequestInternalServerError>>>;
    createWishlist(requestBody: WishlistsV3ApiSpecs.CreateWishlistData['body']): Promise<RequestSuccessResponse<201, Required<WishlistsV3ApiSpecs.WishlistsCreateWishlistResponse201>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.CreateWishlistRequestUnauthorizedError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.CreateWishlistRequestInternalServerError>>>;
    getWishlist(wishlistId: WishlistsV3ApiSpecs.GetWishlistData['path']['wishlist_id']): Promise<RequestSuccessResponse<200, Required<WishlistsV3ApiSpecs.WishlistsGetWishlistResponse200>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.GetWishlistRequestUnauthorizedError>> | RequestErrorResponse<404, Required<WishlistsV3ApiSpecs.GetWishlistRequestNotFoundError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.GetWishlistRequestInternalServerError>>>;
    updateWishlist(wishlistId: WishlistsV3ApiSpecs.UpdateWishlistData['path']['wishlist_id'], requestBody: WishlistsV3ApiSpecs.UpdateWishlistData['body']): Promise<RequestSuccessResponse<201, Required<WishlistsV3ApiSpecs.WishlistsUpdateWishlistResponse201>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.UpdateWishlistRequestUnauthorizedError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.UpdateWishlistRequestInternalServerError>>>;
    deleteWishlist(wishlistId: WishlistsV3ApiSpecs.DeleteWishlistData['path']['wishlist_id']): Promise<RequestSuccessResponse<204, Required<{
        [key: string]: unknown;
    }>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.DeleteWishlistRequestUnauthorizedError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.DeleteWishlistRequestInternalServerError>>>;
    deleteWishlistItem(wishlistId: WishlistsV3ApiSpecs.DeleteWishlistItemData['path']['wishlist_id'], itemId: WishlistsV3ApiSpecs.DeleteWishlistItemData['path']['item_id']): Promise<RequestSuccessResponse<200, Required<WishlistsV3ApiSpecs.WishlistsItemsDeleteWishlistItemResponse200>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.DeleteWishlistItemRequestUnauthorizedError>> | RequestErrorResponse<404, Required<WishlistsV3ApiSpecs.DeleteWishlistItemRequestNotFoundError>> | RequestErrorResponse<500, Required<WishlistsV3ApiSpecs.DeleteWishlistItemRequestInternalServerError>>>;
    addWishlistItem(wishlistId: WishlistsV3ApiSpecs.AddWishlistItemData['path']['wishlist_id'], requestBody: WishlistsV3ApiSpecs.AddWishlistItemData['body']): Promise<RequestSuccessResponse<201, Required<WishlistsV3ApiSpecs.WishlistsItemsAddWishlistItemResponse201>> | RequestErrorResponse<401, Required<WishlistsV3ApiSpecs.AddWishlistItemRequestUnauthorizedError>>>;
}
