import RequestService from './helpers/request/request-service';
import { BigCommerceStoreApiConfig } from './index.types';

import AbandonedCartsV3Api from './apis/abandoned-carts-v3.api';
import CartsV3Api from './apis/carts-v3.api';
import BrandsV3Api from './apis/brands-v3.api';
import CategoriesV3Api from './apis/categories-v3.api';
import CategoryTreesV3Api from './apis/category-trees-v3.api';
import ProductModifiersV3Api from './apis/product-modifiers-v3.api';
import ProductVariantOptionsV3Api from './apis/product-variant-options-v3.api';
import ProductVariantsV3Api from './apis/product-variants-v3.api';
import ProductsV3Api from './apis/products-v3.api';
import ChannelsV3Api from './apis/channels-v3.api';
import CheckoutsV3Api from './apis/checkouts-v3.api';
import CurrenciesV2Api from './apis/currencies-v2.api';
import CurrentCustomerApi from './apis/current-customer.api';
import CustomTemplateAssociationsV3Api from './apis/custom-template-associations-v3.api';
import CustomerLoginApi from './apis/customer-login.api';
import CustomersV2Api from './apis/customers-v2.api';
import CustomersV3Api from './apis/customers-v3.api';
import EmailTemplatesV3Api from './apis/email-templates-v3.api';
import GeographyV2Api from './apis/geography-v2.api';
import InventoryV3Api from './apis/inventory-v3.api';
import LocationsV3Api from './apis/locations-v3.api';
import MarketingV2Api from './apis/marketing-v2.api';
import OrdersV2Oas2Api from './apis/orders-v2-oas2.api';
import OrdersV3Api from './apis/orders-v3.api';
import PageWidgetsV3Api from './apis/page-widgets-v3.api';
import PagesV3Api from './apis/pages-v3.api';
import AcceptedMethodsV3Api from './apis/accepted-methods-v3.api';
import AccessTokensV3Api from './apis/access-tokens-v3.api';
import MethodsV2Api from './apis/methods-v2.api';
import ProcessApi from './apis/process.api';
import PickupV3Api from './apis/pickup-v3.api';
import PickupMethodsV3Api from './apis/pickup-methods-v3.api';
import PickupOptionsV3Api from './apis/pickup-options-v3.api';
import PriceListsV3Api from './apis/price-lists-v3.api';
import PromotionSettingsV3Api from './apis/promotion-settings-v3.api';
import PromotionsV3Api from './apis/promotions-v3.api';
import RedirectsV3Api from './apis/redirects-v3.api';
import ScriptsV3Api from './apis/scripts-v3.api';
import SegmentsV3Api from './apis/segments-v3.api';
import SettingsV3Api from './apis/settings-v3.api';
import ShippingV2Api from './apis/shipping-v2.api';
import ShippingV3Api from './apis/shipping-v3.api';
import ShippingProviderApi from './apis/shipping-provider.api';
import SitesV3Api from './apis/sites-v3.api';
import StoreContentV2Api from './apis/store-content-v2.api';
import StoreInformationV2Api from './apis/store-information-v2.api';
import StoreLogsV3Api from './apis/store-logs-v3.api';
import StorefrontTokensV3Api from './apis/storefront-tokens-v3.api';
import SubscribersV3Api from './apis/subscribers-v3.api';
import TaxV3Api from './apis/tax-v3.api';
import TaxClassesV2Api from './apis/tax-classes-v2.api';
import TaxPropertiesV3Api from './apis/tax-properties-v3.api';
import TaxProviderApi from './apis/tax-provider.api';
import TaxRatesZonesV3Api from './apis/tax-rates-zones-v3.api';
import TaxSettingsV3Api from './apis/tax-settings-v3.api';
import TaxZoneCheckV3Api from './apis/tax-zone-check-v3.api';
import ThemesV3Api from './apis/themes-v3.api';
import WebhooksV3Api from './apis/webhooks-v3.api';
import WidgetsV3Api from './apis/widgets-v3.api';
import WishlistsV3Api from './apis/wishlists-v3.api';

const defaultConfig: BigCommerceStoreApiConfig = {
    storeHash: '',
    accessToken: '',
};

Object.seal(defaultConfig);

class BigCommerceStoreApi {
    readonly config: BigCommerceStoreApiConfig;
    readonly request: RequestService;

    readonly abandonedCartsV3: AbandonedCartsV3Api;
    readonly cartsV3: CartsV3Api;
    readonly brandsV3: BrandsV3Api;
    readonly categoriesV3: CategoriesV3Api;
    readonly categoryTreesV3: CategoryTreesV3Api;
    readonly productModifiersV3: ProductModifiersV3Api;
    readonly productVariantOptionsV3: ProductVariantOptionsV3Api;
    readonly productVariantsV3: ProductVariantsV3Api;
    readonly productsV3: ProductsV3Api;
    readonly channelsV3: ChannelsV3Api;
    readonly checkoutsV3: CheckoutsV3Api;
    readonly currenciesV2: CurrenciesV2Api;
    readonly currentCustomer: CurrentCustomerApi;
    readonly customTemplateAssociationsV3: CustomTemplateAssociationsV3Api;
    readonly customerLogin: CustomerLoginApi;
    readonly customersV2: CustomersV2Api;
    readonly customersV3: CustomersV3Api;
    readonly emailTemplatesV3: EmailTemplatesV3Api;
    readonly geographyV2: GeographyV2Api;
    readonly inventoryV3: InventoryV3Api;
    readonly locationsV3: LocationsV3Api;
    readonly marketingV2: MarketingV2Api;
    readonly ordersV2Oas2: OrdersV2Oas2Api;
    readonly ordersV3: OrdersV3Api;
    readonly pageWidgetsV3: PageWidgetsV3Api;
    readonly pagesV3: PagesV3Api;
    readonly acceptedMethodsV3: AcceptedMethodsV3Api;
    readonly accessTokensV3: AccessTokensV3Api;
    readonly methodsV2: MethodsV2Api;
    readonly process: ProcessApi;
    readonly pickupV3: PickupV3Api;
    readonly pickupMethodsV3: PickupMethodsV3Api;
    readonly pickupOptionsV3: PickupOptionsV3Api;
    readonly priceListsV3: PriceListsV3Api;
    readonly promotionSettingsV3: PromotionSettingsV3Api;
    readonly promotionsV3: PromotionsV3Api;
    readonly redirectsV3: RedirectsV3Api;
    readonly scriptsV3: ScriptsV3Api;
    readonly segmentsV3: SegmentsV3Api;
    readonly settingsV3: SettingsV3Api;
    readonly shippingV2: ShippingV2Api;
    readonly shippingV3: ShippingV3Api;
    readonly shippingProvider: ShippingProviderApi;
    readonly sitesV3: SitesV3Api;
    readonly storeContentV2: StoreContentV2Api;
    readonly storeInformationV2: StoreInformationV2Api;
    readonly storeLogsV3: StoreLogsV3Api;
    readonly storefrontTokensV3: StorefrontTokensV3Api;
    readonly subscribersV3: SubscribersV3Api;
    readonly taxV3: TaxV3Api;
    readonly taxClassesV2: TaxClassesV2Api;
    readonly taxPropertiesV3: TaxPropertiesV3Api;
    readonly taxProvider: TaxProviderApi;
    readonly taxRatesZonesV3: TaxRatesZonesV3Api;
    readonly taxSettingsV3: TaxSettingsV3Api;
    readonly taxZoneCheckV3: TaxZoneCheckV3Api;
    readonly themesV3: ThemesV3Api;
    readonly webhooksV3: WebhooksV3Api;
    readonly widgetsV3: WidgetsV3Api;
    readonly wishlistsV3: WishlistsV3Api;

    constructor(config: BigCommerceStoreApiConfig) {
        this.config = Object.assign({}, defaultConfig, config);
        this.request = new RequestService(this.config);

        this.abandonedCartsV3 = new AbandonedCartsV3Api(this.request);
        this.cartsV3 = new CartsV3Api(this.request);
        this.brandsV3 = new BrandsV3Api(this.request);
        this.categoriesV3 = new CategoriesV3Api(this.request);
        this.categoryTreesV3 = new CategoryTreesV3Api(this.request);
        this.productModifiersV3 = new ProductModifiersV3Api(this.request);
        this.productVariantOptionsV3 = new ProductVariantOptionsV3Api(this.request);
        this.productVariantsV3 = new ProductVariantsV3Api(this.request);
        this.productsV3 = new ProductsV3Api(this.request);
        this.channelsV3 = new ChannelsV3Api(this.request);
        this.checkoutsV3 = new CheckoutsV3Api(this.request);
        this.currenciesV2 = new CurrenciesV2Api(this.request);
        this.currentCustomer = new CurrentCustomerApi(this.request);
        this.customTemplateAssociationsV3 = new CustomTemplateAssociationsV3Api(this.request);
        this.customerLogin = new CustomerLoginApi(this.request);
        this.customersV2 = new CustomersV2Api(this.request);
        this.customersV3 = new CustomersV3Api(this.request);
        this.emailTemplatesV3 = new EmailTemplatesV3Api(this.request);
        this.geographyV2 = new GeographyV2Api(this.request);
        this.inventoryV3 = new InventoryV3Api(this.request);
        this.locationsV3 = new LocationsV3Api(this.request);
        this.marketingV2 = new MarketingV2Api(this.request);
        this.ordersV2Oas2 = new OrdersV2Oas2Api(this.request);
        this.ordersV3 = new OrdersV3Api(this.request);
        this.pageWidgetsV3 = new PageWidgetsV3Api(this.request);
        this.pagesV3 = new PagesV3Api(this.request);
        this.acceptedMethodsV3 = new AcceptedMethodsV3Api(this.request);
        this.accessTokensV3 = new AccessTokensV3Api(this.request);
        this.methodsV2 = new MethodsV2Api(this.request);
        this.process = new ProcessApi(this.request);
        this.pickupV3 = new PickupV3Api(this.request);
        this.pickupMethodsV3 = new PickupMethodsV3Api(this.request);
        this.pickupOptionsV3 = new PickupOptionsV3Api(this.request);
        this.priceListsV3 = new PriceListsV3Api(this.request);
        this.promotionSettingsV3 = new PromotionSettingsV3Api(this.request);
        this.promotionsV3 = new PromotionsV3Api(this.request);
        this.redirectsV3 = new RedirectsV3Api(this.request);
        this.scriptsV3 = new ScriptsV3Api(this.request);
        this.segmentsV3 = new SegmentsV3Api(this.request);
        this.settingsV3 = new SettingsV3Api(this.request);
        this.shippingV2 = new ShippingV2Api(this.request);
        this.shippingV3 = new ShippingV3Api(this.request);
        this.shippingProvider = new ShippingProviderApi(this.request);
        this.sitesV3 = new SitesV3Api(this.request);
        this.storeContentV2 = new StoreContentV2Api(this.request);
        this.storeInformationV2 = new StoreInformationV2Api(this.request);
        this.storeLogsV3 = new StoreLogsV3Api(this.request);
        this.storefrontTokensV3 = new StorefrontTokensV3Api(this.request);
        this.subscribersV3 = new SubscribersV3Api(this.request);
        this.taxV3 = new TaxV3Api(this.request);
        this.taxClassesV2 = new TaxClassesV2Api(this.request);
        this.taxPropertiesV3 = new TaxPropertiesV3Api(this.request);
        this.taxProvider = new TaxProviderApi(this.request);
        this.taxRatesZonesV3 = new TaxRatesZonesV3Api(this.request);
        this.taxSettingsV3 = new TaxSettingsV3Api(this.request);
        this.taxZoneCheckV3 = new TaxZoneCheckV3Api(this.request);
        this.themesV3 = new ThemesV3Api(this.request);
        this.webhooksV3 = new WebhooksV3Api(this.request);
        this.widgetsV3 = new WidgetsV3Api(this.request);
        this.wishlistsV3 = new WishlistsV3Api(this.request);
    }
}

export default BigCommerceStoreApi;
